### ISSUE TITLE
Error in configuration.yaml after hacs and rpi_rf Update 

### ISSUE THREAD

**Issue by FreddyMbN** [markvader/ha-rpi_rf#32]
hi, 

i have an issue with the configuration.yaml since i have updated homeassistant.
i also updatred hacs, rpi_gpio and rpi_rf. 

ERROR-Message:
bad indentation of a mapping entry at line 58, column 9:
        gpio: 17

Has somebody any clue about a solution?

```switch:
 - platform: rpi_rf
    gpio: 17
    switches:
      Stern:
    pulselength: 300
        protocol: 1
        code_on: 1394001
        code_off: 1394004
        signal_repetitions: 10
      Druckerbeleuchtung:
        protocol: 1
        pulselength: 300
        code_on: 1397073
        code_off: 1397076
        signal_repetitions: 10
      Nachtischlampe Freddy:
        protocol: 1
        pulselength: 300
        code_on: 1397841
        code_off: 1397844
        signal_repetitions: 10
      Lichterkette:
        protocol: 1
        pulselength: 300
        code_on: 4195665
        code_off: 4195668
        signal_repetitions: 10
      Nachttischlampe Jill:
        protocol: 1
        pulselength: 300
        code_on: 4198737
        code_off: 4198740
        signal_repetitions: 10
      Standlampe:
        protocol: 1
        pulselength: 300
        code_on: 4199505
        code_off: 4199508
        signal_repetitions: 10

**Comment by FreddyMbN** [comment]
oh, that was miformatted by pasting in.

the error occures allready by writing this 

```switch:
 - platform: rpi_rf
    gpio: 17
    switches:
      Stern:
        ulselength: 300
        protocol: 1
        code_on: 1394001
        code_off: 1394004
        signal_repetitions: 1

**Comment by markvader** [comment]
> oh, that was miformatted by pasting in.
> 
> the error occures allready by writing this 
> 
> ```switch:
>  - platform: rpi_rf
>     gpio: 17
>     switches:
>       Stern:
>         pulselength: 300
>         protocol: 1
>         code_on: 1394001
>         code_off: 1394004
>         signal_repetitions: 10
> 

gpio: and switches: need to aligned the same as platform:

Then the switch name "Stern" is set in 2 spaces, then pulselength etc are set in a further 2 spaces

**Comment by FreddyMbN** [comment]
omg thx i didnt think about it, cause this configuration worked for months

**Comment by markvader** [comment]
Glad you got sorted, let me know if you have any other issues.
